video: tegra: host: gk20a: fix gcc-6 compilation
drivers/gpu/nvgpu/gk20a/mm_gk20a.c:124:18: error:
'gmmu_page_masks' defined but not used [-Werror=unused-const-variable=]
 static const u64 gmmu_page_masks[gmmu_nr_page_sizes] = { ~0xfffLL,
							  ~0x1ffffLL };
                  ^~~~~~~~~~~~~~~

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Max Krummenacher <max.krummenacher@toradex.com>