gpu: nvgpu: fix gcc-6 compilation
drivers/gpu/nvgpu/gk20a/regops_gk20a.c:344:40: error:
'gk20a_runcontrol_whitelist_ranges' defined but not used
[-Werror=unused-const-variable=]
 static const struct regop_offset_range gk20a_runcontrol_whitelist_ranges[] = {
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drivers/gpu/nvgpu/gk20a/regops_gk20a.c:350:18: error:
'gk20a_runcontrol_whitelist_ranges_count' defined but not used
[-Werror=unused-const-variable=]
 static const u32 gk20a_runcontrol_whitelist_ranges_count =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

drivers/gpu/nvgpu/gk20a/regops_gk20a.c:366:40: error:
'gk20a_qctl_whitelist_ranges' defined but not used
[-Werror=unused-const-variable=]
 static const struct regop_offset_range gk20a_qctl_whitelist_ranges[] = {
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~

drivers/gpu/nvgpu/gk20a/regops_gk20a.c:373:18: error:
'gk20a_qctl_whitelist_ranges_count' defined but not used
[-Werror=unused-const-variable=]
static const u32 gk20a_qctl_whitelist_ranges_count =
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Marcel Ziswiler <marcel.ziswiler@toradex.com>
Acked-by: Max Krummenacher <max.krummenacher@toradex.com>