tegra: Don't make address-of-packed-member warning an error
Causes build failures with gcc 9.3.0.

> drivers/video/tegra/dc/ext/events.c:194:36: error: taking address of
> packed member of ‘struct <anonymous>’ may result in an unaligned pointer
> value [-Werror=address-of-packed-member]
>   194 |  tegra_dc_ext_queue_event(control, &pack.event);
>       |                                    ^~~~~~~~~~~

Also in drivers/media/platform/tegra/nvc_utilities.c and
drivers/video/tegra/dc/ext/events.c.